apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sample-nginx-application.yaml
  - monitoring-app-of-apps.yaml
  - sealed-secrets-namespace.yaml
  - sealed-secrets-application.yaml
