apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - qrly-namespace.yaml
  - qrly-database-sealed-secret.yaml
  - qrly-application.yaml
  - qrly-ghcr-sealed-secret.yaml
  - qrly-github-token-sealed-secret.yaml
