apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qrly-pr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - pullRequest:
        requeueAfterSeconds: 60
        github:
          owner: Blues-Brackets
          repo: qrly
          tokenRef:
            secretName: qrly-github-token
            key: token
          labels:
            - preview
  template:
    metadata:
      name: qrly-pr-{{number}}
    spec:
      project: default
      source:
        repoURL: git@github.com:Blues-Brackets/qrly.git
        targetRevision: "{{head_sha}}"
        path: helm/qrly
        helm:
          releaseName: qrly-pr-{{number}}
          valuesObject:
            imageTag: "pr-{{number}}"
            imagePullSecrets: ghcr-credentials
            postgres:
              enabled: true
            database:
              ssl: false
            ingress:
              enabled: true
              landingHost: qrly-pr-{{number}}.alfa.bluesbrackets.com
              frontendHost: app.qrly-pr-{{number}}.alfa.bluesbrackets.com
              backendHost: api.qrly-pr-{{number}}.alfa.bluesbrackets.com
            landing:
              replicaCount: 0
            backend:
              origin: https://app.qrly-pr-{{number}}.alfa.bluesbrackets.com
              userRegistrationDisabled: "false"
            frontend:
              backendUrl: https://api.qrly-pr-{{number}}.alfa.bluesbrackets.com
              unavailableRedirectUrl: https://www.orlen.pl/pl/kariera
              userRegistrationDisabled: "false"
      destination:
        server: https://kubernetes.default.svc
        namespace: qrly
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
