---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: qrly
spec:
  encryptedData:
    .dockerconfigjson: AgAovSX59QdgSX4dxDzQ3EekZNNMIV9P2vW53WGfKN+9rY/+Srp6WeIb7LzgRzFH9aJCcowABYtoSfechaNVe74/hiswM/G8rbD0V6nAAsGRTrDiJzqhmwWlB9BIKS8FhddiGeCe9UL1MzZzlOPpOI/Jo8sHPQXrsU2FfGvfQyGoW0exNlR84S3g19fKxfopLgIIKA8y9NTdMWUHi1Lf7oJeMntpUAxnX4g49oSM6y2cZVMXLQqb54oaRzNGorAHckiwFqhnNNV13CYqLR6bOvWwO7V5/rtX4fFcCkrt1vcjYca55Fgat648eKcnrw8+CzEFwEAJZEBPOariTpw8jbNz8RMtq8C+aiEMVWMOHcNSt/M35uaBKP6sFgzki+A9AHD+NOwbi7sqALC4DErZ5M7QV6GnvgnTL5nI8i1heuOthAdmiKtz4qaCVHsnNocnX5CU9YbLzZCZN57WVjxDHWPO5s28xQYftn7hn0tDBh5MQvf8qTosMHH6kk451iYdXLSynicC2NAbHBcD495X20RoHBUZM+WAsihoKi7mb1CqE1aImF2z8qGfQH86Oo1m9J7yVQz/aRnxymH51mxjBEOVPGmP1E9tBOinBLd6nLeUKlcy3ukA741zvyBVzyBejcu+mUOxQ2UufaBM8DHGqneCWw1Cc4boUuDqTFy10KPcWaL2CZQeycOxbLYnbGwpanRxGkW4VKvVV2ctZReUEAUT+VUjD8nFOzczid8ln/l0INRVJnQrRtKl9CmmA8Nntux2+g//wnbqDM7jTJ8NcrYE3YIXPozGVTiMwDnSXWEk7tC6dXrXNtk9rYvwjoUSrHeKTdUPMiQ/hdhgNQZ5ddBATTrkM7yHh5VJUGLsaw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      name: ghcr-credentials
      namespace: qrly
    type: kubernetes.io/dockerconfigjson
