---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: qrly
spec:
  encryptedData:
    token: AgBJqeYnkdmgzAUtpwSJUTmZPUWYie3Cf9983wReNokq8u6x6K936FgnXP89Dzc4Df7qyAKFAFeaNxXa8GKIjg73s5zqmNcoDujbNpDrZn9FCrXWnHKGUUQKbtYFR3V69+MhzER2kr19i2QmxJY/GBcWndjU/dYNS0oJ2rSg3QvHU0et6XvtwuE9GzkkcpoGXIywSA/DMrERu1ahshi8Bey3FLVL9IvNOC1EhBD8MFaIOVwaPb1YK4K7RVTbbdz1OEBj3Ub5GtHeiSVxHB2aJ7iM5ztWNNOio0G6jnJYggHodl8ZFZfOldxiXrvf0Ra4ncVP7A+H6wMoFokVb7E1EOomrzSARu5Z5zibB29ufFcHB5ESzlpXN1EVexkDl3E+R2qBGaIPz2Mtz0OjHevtUzvQ1s/iGPHAoc7QemVfaK2Jr2JSWgP3gOuKGs2EWHQfqN6fCRnkBbZG+xBH4rVit5NeE0kQe+wZ0Zt3KCVq3v/25SZAZJRzsc98xF3JzdYggNS2U+enJtGz91HpWWip77KBK0uAByF/jd5InK1bYmPyQvdqcLo1hLe/2DlFXlx3aCQzZWlOOxMYeawqE2ROi1Bi/05gXmhVRWCMBrwCnpPnqjrEcfMz7cIa++ytk7JeoKq1UAf5OtO1Vf1rWhtoYn1kXOXvw5R7tiv5P8Akog6SGB7+KcNaBGWn7PkK78gz0dvIJHf+1tVTOxclBbkk66fWbXuUaPgLXZLgjGMAgKUqrF2WHXWI8pSc
  template:
    metadata:
      name: github-token
      namespace: qrly
