---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qrly-database-secret
  namespace: qrly
spec:
  encryptedData:
    DATABASE_URL: AgBWXn13/DI8NUSdXEuJAXZjemdfo+QaqC7rpvTyZ+QYq/tnA8zOevbal1NjUX/C+ssvSuQqdOMIv8d8hv114P9cH1UOxrTNxe2rE4FWtr/zUZZJuftuoTjVwsHuMoquk38zOjv5yhaTezF7Ws6QD7ThdjuB9lxevr9paoCi8jOuTPvJikkNaYzepTO/aX2kSt6fP0oQw+/WWFMEgDB0KI7lALNIDZIdX2woMNPHYYGnW/p8gUlfFBxnTKA70IdFlIym+U+QbLKcCCJjBm86G6OFVtqZDaK9GUMERCBJvgJ6XAu5+kQgamnBJ7sqaKXuxoKGsR7MrY06Otm1iJj7Z2/IWrYE+iqOsSf5/0weSLo+qnQM3InQyLBRaAkEpCC0ZLj28T6ReLPUiVI+zdo0jHhrtiurRANh/4/4CX6BXfaBPNfkrZQSCX6ydZw9sMyDEgVd0LtH7SePUR3zJAbcib4N+R+F4eQ9wmUtai8Ji1EKEbrmB4giRr9e4FiEhGkWi9gV8m9PLJkK3M97A0mDr00geckGqyi0haJMPJSg2Mrr3Wl+zEO6lQiw2mpJQz3AvIzMeRdUNLzkNnGRUu/18rHkZ5hHg5hdGDQOIDo2S5Vi/DlRF+pX1DqaMAhMNbBnkAVwUeRTCEmh08x3TlQtLc6hWxlkfG8hvF8sCDF7EP3cHVdzuw4ycSXMmBOEwgG9rggDY/okrfC4xsYu/IAe1o1frOYrOkBQjbPn7pzd3yim2A1MdKtjIBfDdx2Y4pDGT/e6AB3u6+G913umKjIpn5tTL14PIJgcYenFaIFe80hgicqvYy78PsbjNjCM8LxUYB/ioQaAYW+P2bDa66UtFzeL11eByOmCQuH7RkcwRtUIt9AJ8zIl6HEG8poNUtSp+gbi3AJcd8xvdOfzmDjAYA==
  template:
    metadata:
      name: qrly-database-secret
      namespace: qrly
