---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qrly-github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgAkynNyUYUYu9Z5bxKkGD+fIzzCFrg9iSnXfcMOFAVGq65rm/uV/3GxDp9Nym/fDkY6qHeB4WiMgIz9AP/tALCcAFw5aBdFndv0VqTDu8Ykt1UiAXOnUrFDpmKVPSxXOJFKuEl2djHBVQGEVdeX6MQKVyVySiCh5LjqBrTCptWSzrQRSeMPAtop1H8ulPPc0BTzayaQXX4jbF8eDJLATk9JkWFlgQ1X91IFSvewFdtz2MCoAAZXp2eEwTx48/hWwmhvZoxBP0igHFCrZ9qS8O1UqwKA5YLx9CQVRj0Nxol5I85vBZhRRTPeEgFrGDzISFlzouzt2YH9WTaD6FPdS7t0qZXjIVjmNd0L9/WaOo2ow0jXVlFuaeD5cloEKQjqzxw+DEUiJ1kbyGnpWfSbm737QFu+DP1eyYi3k8wLxcG1LXh8VOWsztMHKXgOQIbh8nv642LJ3PZEBke6aeloWQ6aCRXwQGn9V+m9eoSQIpFgl+PlBLQ3x+jMysuctfTn6qlQQ3rWcHDJLfF3YZZfQxzioPbJSrIEYd4L8GkXMGQ6uUCF98ALwCgxEb9XoLHbpE4ge1zqgXT+5/X643Rufs30SijA1BE1wySFsopWHslrbO4VqK5yzF5rRXOivM9koIypZyXW19bPbDM5Y7P9ri9alUR3I1JmnR+Z9GdQYgTWEAd45jJy+uHMOUGmqbBzK3hYlt5UmiWvFeDP/AC5vL+LJ9uEDjX3yDmJjHA+f0+grUvM4Mmi750F
  template:
    metadata:
      name: qrly-github-token
      namespace: argocd
