---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: qrly
spec:
  encryptedData:
    .dockerconfigjson: AgAcT2+uZXld2NlzCV6u7dUhQ1H4Eh0Yrj1yjWKrJYu4KqjzSq0F+Tt4yfUHDzAiOnxuUvSyZDK3K/9htinvvXjGaYQLExfisqWsFPQ9Fren+i7hVthU4gISW/afsLhhrQ2LSRsB0Xm1HNA3ckXAgvkJebnyX+2Kt3wD46bSR5j2dRJbQLwr1sF/owMy5P7Bxvf0S6ecmVmWyvIaR9znaIqP9dS8v6RoX9V5wDXUl/3B53ZBR6ifMvwzLZNkTpfyCxGClYFmQAJEIOQZq5OTBGn0jfwdxKLxtls/W+aZXYhXOG8TNCbzkH8kLLutpONF+fXQXVEHy2wXchaV8APMG0mj0ZSOjSyoHwJ5CH9/w9UZKmYjP55XSLnVhbtbGUx3zPCXNz3+FObew+HTJxDeRvV8npHeHp5lMrgX92caOEmoovAMJlOqirYNV3sb8OGj54DyWcfvkc3hyF2Bm2iIFFQhZg4z8zEmfiFJQ0lg1TyRL6/hUua6cokYlG6viTHoI0yuasM8DscsK44zg+iByaB8IpIKLzIl1R8VitZAmRhaTW59++LfUUIaRP6C8fBcAboI4tQLGJj2suZknfs3INBZJ6hEz3rHYfGYnEXJ6dzUfQcZs1BX9KPZLaka2MtXpdrj0rlkCvpzgZtc1USvOEb2eEJ+S/OFdHgFpLcqqg2pQRaViZ8jMGh1gvhlBzJhzLn7RZeVLgleWTcJBr6DbtylRUC7lLCrGSgRIHOB3FDgOGoE2DXO1RWCEl5w00zQhZ25MhB9Xh/mqyD7NbAvu2tCi1oBGSFHidHyCH6F0KHGJiuEVnw6IIv+jcRrscFadoJO
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: qrly
    type: kubernetes.io/dockerconfigjson
