---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: czeq
spec:
  encryptedData:
    .dockerconfigjson: AgCwxDOl+xIWQgP2X+NXqnex6Ywemafp6sV+S2PbbYySxgRQbkDNCVzhbVzpgJYxZvsFgC1a+DnMZBngrY9H/G4hTr+zlvApsUR5nLx13Bi7myW/5FkUJgR3OdL+gMRvhYMYu6OFaUHSRYIeMgDPubtemlu8Y4OrG+FxDORKY6F8sgcwKVeWh032bW5K00/TV7yhsnXRVqXUFuHK3FgGxL/m752ZoxO6xyo/W2rdLszE1BMldeckG/EFVJ71bC7VVldDyjbex25U9Rafic5eSd3RqabD7WeebJaA0JkTPNvmVE0QfTRhEOyRFoGr3yG3xlkXIEZHaQI4jUQ6fjWfkft41+gTkkJ5nHVZbaIJtqPIOJdZ9oLgzWn4Oekgzejd4IvtDRKN87OpkUJ16fJcplmJa+CRMgJ0qy/oPtdU0rqxYD6YfwCW0ns18ThryGiwGU8mErBwPK1uuPbfJPAtOVr+Y9R6YTF/SAb0vGuVuWs5R0ddZLYyR/ipC8Kqatl+qY3lbpMb8p2CPJ39pnzW1rrgcEgAz3G7g8RUsCJ23nWXezfYXzWpjt8PhWGHwtOSQxgUNvjXpjV4hkFuB4VZtEGGWiMUGJSpnmpFYbFFrFNoJcONz3FDygy2GLWbTDcU1AnAldQGGBYeycADQo7nnziEVaMrvKoa/oKDxTJp8ab2Ul/tybUQ6bg8xTISo3LEz5gkH4veJSDXTHMUn8kaExxrfnaA8bOhiOBIhgyycZwFNakh+hslSU6fsP0fY7KM2WonVXpyepqRrd5QlIocybyIOI348VMn/QtJbGWWWyJWWNMFC9Ya3yTVuc79remsT92C
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: czeq
    type: kubernetes.io/dockerconfigjson
