---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: czeq
spec:
  encryptedData:
    .dockerconfigjson: AgBiId0o2sLzPJEDw2OYVaQevvYdQwMG8ozbtIdZAjaz4AD9X4EW3Bjdp3JD1N3lS3uP6CxnBBDxkAW8AmpuHzbUVWpz4BS51uOqaNiRWJ0jCZl76pdLNgvxIeO4hcSlHIF0Nhe1/VEiwOe53Ky43OKfR6wk9s6ZfjHmdp9uXX7aEJwVnQPnWRbbiomCHU2YqF59amYqvVOVloUWK6T3wZpMyJNVgv8tXkCVSk0z60eg0p9ofJUvAYVPEr9I3jkR4fLM+ujPSAyCCpsd1Tfju9vCEAeYVXNX4R3IjizXlt3sVPoxdSgPyTg8Ew/S9PtDmt+wMvh0CkPpX7qMMKDSB7w3LJ0yJzjV+i8OLqcheRF6BknO9up45pwuFrvtqofAKpXbjJhJE18z2vPqJIFBGyi+86xahX//rmzv59IvVk5Sz+aMmPXvqHy27nAzJAsZFuSzt/p1VaNZO1K+9SXh/fJVzvKhh+SGOSDdNR2R0ezrlwvLTq67njyZCkjAMSCCKPDH7G5H8fbKO3FUvTUKGAlDH3R6R8jnU/SFB4lW2p/tnQHIknduv3EcVuKVEbmsk/Vz/d3Gpdb40FoQHnUv5eL8bYUqNbTCnaNIJOcLq2ZDtRpw9UlzGrzOQ15iGA8thTRGBO3ujwi9jYaVn+NIaY6UGfklk3uc0n4heRwbwYyY2QQAHH6gEI8nHzSYCnm+u1A+MXhw87EsAlFRIWwFXUo2z//QqWDwyh95UzsDNhW5S0spE5EPdGD9MtQJMwQlFphaHA7vNilhGMZAM/6fzGcpuNSNub/qTpzx4Sd40eVJrvSEKC7u6q5KukCh0IQbqRs2
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: czeq
    type: kubernetes.io/dockerconfigjson
