---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgBPoK1R8K28NDPbqUSG4GX26ghQJlNwM9qGKjSpvfd50jcqd9BVy8/OywlYfF4FeubPLNADN3vam7Q7a41dF/8JBj7JwNUY734QjEovyDKrYrjPuAr6jIV8BTAQUYc0rbKj5F6SnGRvfMSAfIKYsav0hQxqxQAfNq/OXFACRwBoRXDYZQDIA3AAPC2OOyDfP8vNIetrdOfLyb0rcbKUqUpyoWw1qDpRgNvFD19JqBZyyK3E5SMG6GLh8HtIJkmf2J6e1EpHGAQ/9JSCYpagXG0PduNz8t18lV03r7mrr+BNbwHqsrPoznmxyl/T913IaGOXcey5ZobiW3mCRsj9G6CG/1FPSZsMluv3OixJl29wggkEh/g79Rmdn4xMXjQk7XaWYCf/6pR1NaT8xvVOHR5nIvQu2GqzKmDLOytIJPPp0LGkeE+8uFgt9TryR7xq7IeD28jhasppsMrWPFuO4sphTRUJ/JjVHxmrDQYC/Sq1aoA9+n8Awt39r0o2ZAlmOUur9naiEedw4aVhn3b8U52aF0aXGTfXF/cWeyDi8MV6Byt1YRI40Fma78xIg70O4jevVa39CVXdPDxZCPI3oLtjHkjCljEvtlByjc8dKGTfkvc+NX/tHQkScltpoVEjFMhZo9GMabzW5cIDd1ctPvhgtKAoUOin1IMoeb4+Gy2Tm+jvtyiOyTz1CcJxdJGl9+2eI6/2UKwX4S00SJhCkYlLXApDtkOzeQWBnc9bp+PvM3bPKtaVd87p
  template:
    metadata:
      name: github-token
      namespace: argocd
