apiVersion: v1
kind: Namespace
metadata:
  name: czeq
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: czeq
  annotations:
    argocd.argoproj.io/sync-wave: "2"
imagePullSecrets:
  - name: ghcr-pull-secret
