---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: czeq
spec:
  encryptedData:
    .dockerconfigjson: AgBWbI3rbeYCTZAPJKzLmFHfU5+9aNyeOisIAP1XzZjmyHQvK7itMuTi1v0JJcMr6VPBq0xgJk45Qu1J2GkmP0JAGuxm5q7CMtXXCpsVncXeK9dA6BHnM8M/Z8m7JFFnXUgrU/1AIR/ut2TMzECRoUwDhZjUJl4r/KtgwaAcMIceInDbEXNrHLHg7G5I2/MB3Ter4+9wItQOHihuHy+cJ3+606MTErav8yL36Cuo6sFjLJ21wtQMouMcvUUiZvW8E5bo63DwsuvYRu4OgB9wAnJVzPiPZUT5UMFMSkDwLnd7ZQHUQame9ZgAn0pdjIVYVW6OClUdOEGb6hvD6IzF8KqEK5GhyhvPlE4hbqFWiCuBtLtcILx3uxQuiMNZO2ydfz6tRzjLkZ1XtTevEslyhqvMwZPbzBuUlDEZB6djZowSBLgwgX7sPxzVLoivoJtupZnVUmRjxVSU/eYwhXiXYe5IpwF1zK3LTOxTLnnQ3hfxq/KK7OWUK4BAfcjsSQj4QwZ/uN8G2fbqWrKogtKSSnVdYxiY4RGoYjE9vz9InyL6fZKudRmINPE+f1/TqEBkXbCKK8qpez0JIydfd/iMMpK5sCPHJX6Ypzm87zRXMpjER3m3QZ9/e2McJw1s6LI83e6Ijl817lWsuw7NlK6keju+/hV5+8D5+bWy9quGhPIem0HA2mWioRrxCFz46GvF1YXUlzdb70ReksoIrv49q0n4PtOZQf8b6ApaVxXCAYpEJFE3MxYM/94oLc8ZiqBepLj/KxJ9D6qTPslNxRjaWf5KLOv3DRNi8GWAyz7HRftzQsQQpEScbmc/jIexkW9IvNM8
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: czeq
    type: kubernetes.io/dockerconfigjson
