---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgCyAndTvGl4acQZkaRPR/oCQ88xfctad98005vCdWwdWxUt+RYy8nQmvY5pECSdPXGU3BpkOwl2eNfqiPjdItSOPtDA4ow4VSPRrJjwwsSO0eZH75RhjXt3GX7/B5jBC43xpkjgY91BcYmUJCDDMbUdu53oyAf3qYukvn+ITA4CWPmRcS8BO3HnuKcO/mZXBaWlXPSFeRwl77B5BHRKpYCL1U2je33VusKoJ6dFnwEUwDwEKxrd1JNL2VYbjAdvGac6vkEXK5SS+wRSBWIAaPpqkDKUSTam1aY61d0RMbtlXVoX/b3c11ALLGrRiG7PFXXg5VjTx2bkh5wJetLrbiOoYmAiRCVBLrbyrpuPiRnlElv1vjO3W4ZD6fkeJBN67Uha3Dxefqw6lam0wqTmq9syO0J70clri/XnazKRxZ5icgmkg/I3Aqn/jerriMppyFtRdNrPiBegXy5s9DTdc2zdECA5XgDXeSVBHhLTjZ9bRH0Qls6PWoOa9w1Evsn/BA5HwcMoBkhH8tmDHMc5Z3MSrkf6i3xxFkmIS0t1EBooWMflaERHah0RaHAEbuFIySGInqy29pvDr6UyV4b7iZSSRjOcB4fQKYjGClKyN7o6Kq0MrPQ1+BKCh8/xrFzhWjcYklybFhaeDxVIRZWMUyfaoUQhT8mK0PDujvv4+/awrq9etSoJuHZfa5thVmDEYiETPYRIVFewgBsB/hsUTCaqnQ3fIkJ//3aA/JjpT/KyWieESopGpJRQ
  template:
    metadata:
      name: github-token
      namespace: argocd
