---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgCQ4ln6QvOHJ/n5aXgSjxB9hXcMCexDVXwVB2pdwD1OxthvKPl0stGrkG3xt3z/fZEZDlqs2YL7lVRLBsyyAdKRS3r2BDu59Rusl0038hsrE9hEpI6WLs1X8ZZPvpdcU0okU5xdUfy1xxRd4ElqSmWItN2cqucWI+KHKwKDrLdzEhmhTTMFVKhs95Jymg2K3fETjf5psUlRe5asjb1BF46zbyhpGQeQLzedAiXQhW+jECLVu4n2G2atNf+iXY8/pYPhvdyWPbtau4W4aspzsr6mVE3tooWaPwBaP37SMLXUyEmiiBCwTeUijiL2Ed12Wju6mEfhZBIZbqSaEp7l47SuRv2hBFdGSLiwUf6KCbTznkaW3/93b27LbMUm5hfJx9G/1gykj+fPbvcZfzfEl8eN4pA9wLY2r+hEpUzfbhOoUh78i5IVnhuVLpZ5IjTDYJxH4oyr/u+4N7S0F5DQO4dGUHt6f6ZwWPBSlJD6Rre3vxxNXXzpS5u8tzvlpclhCUDTymhMIKrI8kgkEzoCuw89FvSO9cH5CY0cBoFJlDLET0Tqjzc+uT2latnzDbREPmPhUgrv6/KXemaouECoKMex5bO9DYNn1H0rtBv44d5w7kd8N7vvE9fhiIUIgvEkNaOT6fOhG56vt5+JmU8WM5ONMRXWAv9kyGhBVP/oasHMI+04y3KMtS+ZGQdAJl09GmJfC64g1yI+q9CmMuSOcJXWpNGTyb4ES5VVA+8cUd6ZNpLtn81qGkce
  template:
    metadata:
      name: github-token
      namespace: argocd
