apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - czeq-namespace.yaml
  - czeq-backend-sealed-secret.yaml
  - czeq-cms-sealed-secret.yaml
  - czeq-ghcr-sealed-secret.yaml
  - czeq-github-token-sealed-secret.yaml
  - czeq-ingress.yaml
  # - czeq-application.yaml  # disabled until helm/ folder exists in czeq-backend repo
  - czeq-pr-applicationset.yaml
