---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-local-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAokDiSVfzTF1Q5VIsoKwcr4cZvkS9Y6/cpxOH3DA8VjdgnTHt8httLCB6sZhCBB2dUUEGjqnI1PnImEaij8hA8JOI1BZL062FG3EHtiWg5HtUuFa7oxw2sr4CuUQPe7QcbbSpVgrJUnryqyvs2QnyrqYhfORVdvavDR62G5TLWuKeuS/UGuDTeGO+kq3iwoBvfndlDcuOXafwIhAMf5GhgWUnd3/auJQovW1adNBv4fMQVIxpZU7xTxYJvUlemFiqDHyoSRqORQPbiOkhmtck/plubdgyxEkmIY70+SHrzxRIWk8PLC1S3Y0jn1TekYSmv/X59Qj38KEAuPU5iXBZUrqL1bhNDfeSE61Rx5xleSm81t3EdRHkxjEY7mggkQnZNLzdsFo0UuvTl8Ie3Aj8LhaRE2uiU/SjqXjG6pCKx6Vkf6S5OOXCVA82CUzYYp5V4ymkM3vvX2vAf4Hazl5VUsz4PNeykedUYXjcWTHSYTiU4v2+mfK2j8edDKPK1WJqhBtukWNyQrhkAWps3gELza+Ioja9FJOWpxh9IbQvlWAYrRYwfR4pZl6t0TSbYDmjVRihtIp3AFiJzVd7RKRGMbW+rbU7KKCeRo0z07JyxkXZ/Sl1vR6P4kXpKWGVP+YrPl6AztWT0h5zxekngL3yuGYxkNE+gmRcV+6UANdd/BEF9EAGHzlrHtPx337g0S81YJUBXediHQ+COTV7VSBJQ4AET08Mn2sFPTGndJwAXj+qj5gxHT7ed9Q017ibvPFApq0whLy93FRhTnJ1gygpU+X4=
  template:
    metadata:
      name: velero-local-credentials
      namespace: velero

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-remote-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAmMs6c1UIw9zdPiGqz1TQM/a6QumM+dIIk5ICQo8ik49kGSr70bk94rLJd3RhzEx9V+Bw1IKu0qbLqxqrt5EGsdVLH1NVHgOYTZYy6tBvhQQ7fE1hazFldQHzsLPwiPgd9GyOQ/N6K+7uK2iPXBysxdewJP/AXlLjrRv4wjaHKmXyQjA/BtMpe0dQMidEhyncsDUjGikvpvVljToL38rLO5gp6Kmy1Wd4DjFaRKw/58TYKQpNO1k3FLLP/GpdLlJFIRyt8XVk5QadLWH0S/pGsFe0A2eo/qYffe9QjKTlgP2Maba6sahMMSfUL0ID8aLic07/8iPE7N7nihDL2fr5AEosFeJOATBJ6qw8SBr91GNJX2pWhg4urLGh0exZFeASmSNErkIBG1tCGsep9+jxPoieScLGQDXTt+21jHOAS8kVgNBTXVLLUqLX9xG/+QVExL8u2NZ/2szOsxyssASpQWOM0GWrnM1G/lpID9ZXqDC4nqI0kNjfJZBENQOuf2ZQic80embL8mIPxfrdraniWnrIk0ou8nZ4VXft5yq0He9nUpiTjJVUZijcSWN01BqOBB2k+wePsKawHJM5m8rjnON4kcqfQAc9vh84hXXGx6WXBTxYGIw3AXZGXOBSq3YTEkNaB6n9HNWjOe9Cc5vPhHqZ8BTK1NMUI5WPx0O7G5GUWFyT6ZLaa4/7msgbcKv7YFGAURZ58XLzZThiWATGrbXshzDNiTZxK7wTmW0n8QjnLdTroOpgTdDWSJLAYexTGF2ZOgdo0pMWQSdmFEQZ60atAxcfRZkuWc3yeUpJl/F4zfa6ndnYzK0g+nNSxZLOxJ/rusRjoPDTN1Q5UvAWsvv21
  template:
    metadata:
      name: velero-remote-credentials
      namespace: velero
