---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBQnshiyFcLqtbThZFyvD3XaGoKclz+GklNayJZAM2+W8rAMxt6FV5Q8XpmVtEOVOjYuh16Bz65nkHkGzXubjF0oQx8NuUID/NFDky4vFPTP0oGYNsRFfAchanaKY4I66nrs+AHo8HCU9b2T4OfIyAQJq30Dt8ypy3hVM6p9GxrlOfKbZkUNbL7oMKwp+oIqzkdj/WqxQebsXF7N4CXPIfzfx9Hxvf48r322OHmus+H0WipIsl4rkE8v/mES8x0OZgRQS6sbnwmtyljp2xg6S3quoJ162gCx5jPNx18F+vHE12iHlQjocusuZNtgEBcNZJUsmQwvZX9jSffqcLzTN8VftXpi18TcV03E3S6e6jfJNev7MbyA14dlCskmHGUjVbglFIzTC7ZVBAkhocYDtXuRvge0uNvU/xvy5ZTSGibT8psTrytTdefR7vJzPwH7DX3PNyOV/AZ6B/123KX0orslze11CSZhzTgJ5yGPKm9R2VszTTs5sVDV8C74ab1rxUr11L6OZbe6QxYRA3RmVLbfUzAlOOuOfc7lqPFl32I5cmTxv7HHvD7F2CSZMRL80NTIBR09JdM8Uozo0u1oNdQUiR0MlkeuppO+xiklRDkAraxaIfUTq3sOK3ZXCmhgnx33Ho5I2tmw2qo8EAL3rLke/9eeb4G5UH8a5dtsoQEzb3zKcOkjZqiEmfWsRZ/o72WUiBJgyfscuaBkswhxTD53pf1MlJcMUbyLx+Qx6s/HCP0Wy5cQrPRE4uHBseAUa6pQeLCjYRKGjrYYCdaoEeTkT0=
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
