apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-nginx-html
  labels:
    app.kubernetes.io/name: sample-nginx
data:
  index.html: |
    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>Sample Nginx</title>
      </head>
      <body>
        <h1>Hello, world from sample-nginx!</h1>
      </body>
    </html>
