---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: bluesbrackets
spec:
  encryptedData:
    .dockerconfigjson: AgAoF1KiGlXN6ABb2okvot9TziiKg6XXqFM64ySzGazJjFKcI+wbjuAJBdCCSG5kIblSZwfJEuL9wpZ97Yd5tr7IikrFfRBs24Apja6Naea00I1ehcHQ1seboT1KI7xZsBRcKk8cMza5Lpof4R8QsE1VxP6JYZ7TEePG1ibMyGR1JPH88RlN57S0kkKODl0krSlojeQxQLLRtXezMVeaLiPtfkpnGS1NCLasaABUc/WgNOGFyhb3epogYinrVXFBvcgNNGqsSTBLIt8OMLhia7OHz9vmml+IEc7qE0wqZoXWjB7+N9c6Osg1VWdBjy9EdoVFn7j52/US/t61mURtgMO75enlX9AwnYf1QO+X/0qAUnFWj+I83+wxg6zih0BWUW6zpdU/uSh/BqkD2RoUJqX8TxiXkwInZUbiKoaQ4xscO+8i/Ve6unBu0c71bX3YnkJXRL4C28CA3rQPmfSaJ/O2CtcWsP2NXgn7IuOwBzF6EM1GxkBaxQfsC78YcNtMJrLlwyVIpkKBuT1/726HmjOomo4otVlVYCFkELln2iZqNADAcoMgaRNloNCZ2ImjzIYnWacHkRDxSXuX79721vdYrQYI87yzhnGFyKiYet7nfzQeFLaAR73TaRd+jskH/uZdKqmU2rKgwlxFrYLc7SNVBcxio9dEy0tyDV+LiStIDW9YnazKsSW1+/8cChGvyCn//jXoGLCCGOX4ShLHbbezOXKFYtIqmnuzccXdWc70jBfaRZ1+WxxlY4cnoqsfTxijKsZueVsL2Bpzh8NJk4si30gwc7E4GOIfYJ+Df57ovfgjTyuxBBNkn7XgI5CPqSbH
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: bluesbrackets
    type: kubernetes.io/dockerconfigjson
