---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: bluesbrackets
spec:
  encryptedData:
    .dockerconfigjson: AgCdEDU8YbxCZ2qfsiOLQ7S/mpcuE/Gqnp8Vw9R1mW6nKMq//fw8f7YXjV/9a7TgZxjm/3EuoxcOP75DeqDn3NQZhKbb3iA3lN5NlMpv0sZyRmdrIYMinHUphh+n40LpyR1Xrxl7bL4zyV5yMS8YUXrAH7kiVP9JCw84bW1Sqts6cZohx8ajKwG5uGEoKVnDouFWKOlrCUib/FNjkaZe6QDFycyZX6ExNdSbMtOeLsWFZJHS6waSPpAEXrRMD6lu9Kf+t0tGi7+cZ50u5Fzi0fh1UqMpMw41hCHTUDNdGH0ht7J5cM12HE6Y+FdB8ZEqgGZaT40QhhCz6hzi3ZONxaNpD88A2ijNNgm2wFdt6AQ80QQZdAKDzAMOW1SjVLYjeCZm1lPdwx33tOrsEavVBJ1vOTD4d7jZ8D8EgdO04IHwu+49oAVhTrtI9Xm8hPe8Q1WUqZnYJ3edMehbmLQsALpx0N7d5sPetOAj7kqhGTkhIQbuqjAAyAGfMjpx6wqvi6WfZSJNeaM/fM2a+kNTLS4KLsh6G4co+dHRAVjB6jgUK97/Ca0QNELMdTCgOmHzyXbYbnjjMTPZ/t3mPugSIzewzbn1sLe3bHLvx1k6S+gWXQIs8hldWiflY21eFjYA8FI2zhtNOyh+hvIaepZuadwUEbNUDFCuo5qYv+GsmqmkYJsqDNMCVJPpNfbFYwdIXi9XBNegNrSziCxbyPzVhSEI3nUwDYPMWGPutd2TVZt8cMePgKnauOvVpvrtZpMOeYYI443yrx+9bhBA+mtErkkSCJ/tnzuOnfkGiwrG98sugVhG4FC4An5PJHjJpt1MCNHi
  template:
    metadata:
      name: ghcr-credentials
      namespace: bluesbrackets
    type: kubernetes.io/dockerconfigjson
