apiVersion: v1
kind: Namespace
metadata:
  name: bluesbrackets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: bluesbrackets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
imagePullSecrets:
  - name: ghcr-pull-secret
