---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bluesbrackets-github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgBNRirVbqQz58Z9ZiVY6YExg8KA624A/Gkwaf//Ld16EaLj5Gu+33vPn0WArph6CJU5uj47SvNKdqNZ12/AoV4dza3m8jxtirYA6w0NHl4xTMopJaAU4S3ac2pWJp7Fy55AnCjfY6g7pSSXFbtFwx+bklAID450v4izxifwYmGVlec7RM62eqOKutEPsxTmAjAFcMnJrbj7jloHEf2WkgcqVpkyzzKIdywC3ansdRGN6EW9EfHnd9RJVqzvsZ6wHzi1zpj5QLymleq9gKx/bwvma+CUD6ZEI8tMrP/83Gh59ljck8LAjMnsucr+g4LV+Gg+sRqNRtWsB87akVDzBgrevBUbSSnZJ8UHXUrd5thHtQMDgIREZk3J/23XASoAQGI5UoFfrQ997a6ORCcGcSMuwSVAX5HJS5gzSiIlmoaMoV9EP2fltg9pI6TbaoJYnQVcDeKilRmIL23ivielNFG/8/sRAY6cndLy5BcskEKRtdNvpgZ6Z4wRAPPoXTUqQHHBJ6N7jk+mhs2lQzgWS+pY9RrvAa0MPvrKbupWniWgotAofzgmr8VYZ+9dV4yR3IG8xZJBxX3oGn7VasuOnb5rgANPtJ0QUEJpz5YViy3HNP0wukLeZ+cFW2whEA8AoJJpUEA2HE2bmzI/xbLQR5xCyWFjtI3fnfdUIcMZ6evWthMBO5IjnVJEYul0mRDBGiu2KmrMMhOKFsuoaAfkyEXflaAuuxxqfBCKIJ+fMmQTgNMuzOHEzPpO
  template:
    metadata:
      name: bluesbrackets-github-token
      namespace: argocd
