---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bluesbrackets-github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgBRJHGvYhjFDGu4ox+l32d5OgYtIQVmo91jjEx9c5rfR6/Ho8quU3e90EYR0sWVRy9kRzeqLOR5aCEhBbdgn62GEDvaX7LApTHgtCHkUIxHDdkjKy5lpGL4S6J0f63cp8DL2uAD9989p31bA3rPdp3dRO5UXx8lw8GAm95RdQ7P8aYLvhSiAaUVHX7N+O1SN/w8Ee2EhOuMKMiZbcmnFkGHdn80GnbsIjwH+yVoUSPLMSVYFA38C03OjB3ye+TLF6sJWvHVMtyv9gtXxeMpiMsZ1WFaUGBn2ARGQ3uX5hQIxmcRd+VUmHam5TUnXUWsdyuBL1j5Ji9I73exc9HEjjpgpC5d0r1z8xNcm6p9XPqzAoHiDHyXcAMUlRTDkjasLTuTDhOAs7zPjYqouh4uidvkXsRZY6Mc7yqp8Za1iuRcgC1hnhn+oDL+82F+iU5Li8v5aoBYzbLP/tYFmdv9NxWhahIg1w/t1HEt4Mm8Cvi6Yl1PaZAHOjQcnHPWSaPGPCA9Q4WLgtfVmLbvGTPWW+qyw5xCvesfIpcBqr7N4282c62NU7/E4nP6V+D7Ye2QvLpFFujKBdbJ8hxYxWJD0aioLM/M3YyCiYeeh/q6Sf0CV1j52QDAiruMl/1KqrkH8oLcFvt07uIfHcqJFqDS/4fzKcpUopDeEE0cLKGAmS9pcEpC5/dh2t8Fdm/cLwAFhpGTz581/WSs/Iy5YTu51OF47d9Vx/NgpGi9qmXWcnZCy/+LruYN2X6Q
  template:
    metadata:
      name: bluesbrackets-github-token
      namespace: argocd
