---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bluesbrackets-github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgA2mguzC4EZuY5ozQbWWgq3PC7LcRPj74KbZXYJSFk1M3Mng5/kk+P8POSgS11wPzSSqHEEmvJRw7ODxlG5aSiNe7XLqe85XFvIqozHw+rtK1qLvjvVG7gTkhomOyiFyLlTw3MIs/xsgpUPj+Vl59NkEWa+AIgrdOYchkTwO5P2OQ3RQCBfB189uPyo9WckbqnbqC0hPmjnscZw4DfdEPHwMx7lroZB8r/ZPCYe1c5L5fpF9DIctmhiajDwWhboelRH3be4b1qrfRCunfqQlGiy+JliF7yEHqmKi3zT+MAO7ssa+V0ZuC5p0v8CmqlHMkOh+mmMvgvHgp1XcA6cZqJQ7ipk5M5SArf1IKGxXiIBfCFpJe8yLCOwIyXs9sIk2uzIW8GFWw00+tKcGkJvCFTUitHiFdLeEWjhaWekWuiI6m4yDTgdsEtvIX0ihpH+AqGboLxrz30Oym3SoJfnHBT/HFBhV+TER+VnyGXjHuPNWASbeWRjgEI8+MjwkE/E51ZeAFcZXJkCz0l9HTUFyyoKDyp3f+qPrvnNTRaZ+ILLkEeABycjf2ma3g8MRuTBp6ZIHO5Sy31TF/Rk6nSZ9Nm/FOYeVqwO7xLE+mPsMj48hvFhwZjoQjg6Pvpy187VNF3n1kIBsD4RIsIUFtwKKI0+I2sbUViPG64T58kL4ow85A/neIKj17hdmUtZq/IXUCKvMKkyCy1Ae8crp8h4UWhxHExxh8Fy8JUPqVfOFXvzkPEeqaK1ltLl
  template:
    metadata:
      name: bluesbrackets-github-token
      namespace: argocd
