apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesbrackets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Blues-Brackets/bluesbrackets.git
    path: helm/bluesbrackets
    targetRevision: master
    helm:
      releaseName: bluesbrackets
      valuesObject:
        replicaCount: 1
        imagePullSecrets: ghcr-pull-secret
        image:
          repository: ghcr.io/blues-brackets/bluesbrackets
          tag: sha-5a8ce30
          pullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 400m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: bluesbrackets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
