---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: bluesbrackets
spec:
  encryptedData:
    .dockerconfigjson: AgCPRpoHBmTZPenc4PBL6O9WqmGeJq3kQSw7FgDo4aqEquxxwf7Nq+f8UZiOqaVh1FE7YqsjlZ4zZp3KRYLAgHyvbrKsJgtdXlFCYe1aNJc2CWDciFgmZKuUmT/PKjXYwwDVWFw8oTriE5U7dKzxvZY6qpZD9eXSaRrnQ2QFolQUSxWPJC50ZDckQtPi9gcoosrqZN3bZogHDooDSWzOqA2LD1t7Vpim4TRM6k5s/0wQbQvRHyHBaYWnkkH3XVVET7afbldfN9PYMR2dxs3B/TUH4fEd6EKhF/8usHNKO2iwo//O0j9O6UtyFtFP6N+3wgAPHtS444mYKg2xY/gey2fVP80GijnxbBMXrCLBXgCUhqvXlms7xJz0Jh6i04DwI9i1BeiX6aiwlfGQBFCSltXn5eOoda+fYEQZTdhyoNYImkpqhotbsXvZ1zGYrTP7ODs0qdEcGKB+RMIbkFrVb7kWGln/LOUezDSHq0d/JhZBiBlphsrsHSjWPNYjBMFj4bcTjg+sbq898h+rNDl0UOboQGeUzoNZXjAtJuojyXwLc0DaQDQ88NHG28ZK0+olpalD+SCpm7em1H9Ng+aM1lEMQw24GqSilmGlzzWvUtF6frgNRifBKca8BmSil3emMVQAasvB7JouDZi/xrqKeYHwrK7wnVmSs568hjRJ748AJyd3v+tmn35xaPhb19S+JNz7rSbdjT0Aeb67RZy9j0LhEDsW8QY7AGBMvYAOP3DlBUx/6qGvrXklOYN7ANB/Zro3empBhflXqzA1B6fQan6zbRRmLXbhu638SPvTM7BSLzgU5Sx1i/bGLNNrRc9LVOIC
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: bluesbrackets
    type: kubernetes.io/dockerconfigjson
