apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bluesbrackets-namespace.yaml
  - bluesbrackets-ghcr-sealed-secret.yaml
  - bluesbrackets-github-token-sealed-secret.yaml
  - bluesbrackets-application.yaml
