---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCEIdwXRsRq+OMBbxtzxCZfpCX+Kujy8Ist4UiAtMhuHbF/BNZX07gam2KmLOC1REwLN1NGo0R+ywOSwebR/3Z7A7ACGPtVnywJEr3UGZ5rOne3muAzcKkWOQ6IatGDQdEU/PSTVn+fI+teViZOppER/sEh1UzOjz60Fohb6XRGoafaG5jearK2dh4SZACchDC41Z7J5YT8BgzFiIIL7kDyJcSF82oDfofs4BSaVE0fBAVB7QmmHEbSm6EwChNKgiXwG6AqLap6XhJz+xhxrjwjPVHn/mHioch91jgBsLgLNKMMKoOBwy60qLu3KQiTDkM/E5o6Cm5Ii19vnaBGsWvOmpAxDrpBxvI8kWvQ5fCY5YLrHtJ8bEgSK0C3DlK+AeGhbV3ugQQjCUj9y+Muqp8hwroIvOk9pq/TbN3Qk96i+K6GitmsV23bnj1X64Ieit2w4pe+dbg7F7h6ia7hMkxjgX6FyHxR2Gz1m+ZY7F6VIM1LdAJDd6lpZrZ2loqApHn+b1wYDp2Js2tOLhkat543tDU5l13V3FKsy2n4ILjkOOaaMc+3hZwB188ZhLSdTmlFCFFD9dhTT45jAjY1hNXZRXMg1+1DcmQ9cD9AausdPau8CPuNNbj/MTndWW1mWd6dl+H00w4nt/ECaP24Ohd4Ij8VSVPk5XhukNCxiOcKpayFowpakri5mLg1o4DiPqrl5ePkxhVyy6fV
    rootUser: AgBhlMCPa6LGYS6Q1nIwjg+7Y81f6lKtNFrENRj86rf+fz/BTnVfEGPLbbMpsYN/x2z1Vdqt0ysxuwqqxA17G/DpndgLSz3PoV2zI0R7+TsXWz0zzfs5e0kya9HgkJaChwGgATTAciOkUJNnY2FNH4nGlKAiD/7IPxjN1et7R5xAYMCM7KbCisXsNkamzpNBYs5vFhNqSpOLVOyBC1bMn+GZ+wl5yLSe/qyp8+CbdIWWpGmVW3iDXKXPfIn7NPA8nx4FSHCHxrSZAS5L/tBuGu/Enfjn1IsDkWeNya7Gyvsg635JcvUVByTw2wvHYH18GqvusQKW28eCMCPfnvnwYNPLB96hewXOC2Cltkl7ksoOw7z3WXkyJMvd0g8JM10mkwtabtxDr/zMDDifnmRohSuIG+86LWN/eLWXntePC5QGp7nzlimXEnHUocmzxvC8ak0wdcwN79y0P2yjAnooN2H2bmR9eAxBUOctmjTw6KufVU96syILTtfZCxCODXE0ZfW9wf3Mf+aVb9kC+bGfHfyXHcTtnrLXnQPfXfAlpgYpUZ+EmpfxDJeXv0CJaOCFZ/hgZs00LMmUVNXMy2LMFwM+A1CnloTR0b6K3bSSJr/S9fU86n2DyQVq6O31MWNcuIe84P5AuDjA3cC2m9VVJz6TcSZYhB2wjEyTBlD+T59NB9WLPcrRoKKZuttYjTVbb0iu/L2yrA==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
