---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: observability
spec:
  encryptedData:
    webhookUrl: AgCThmc22pbmSu4WktIojRePG163wCQMh40j+qxyWM6GwUdCWKQt9xwhhqv6RLM2O7v94btKVz2ekQfnEcm2Fh5l85bniBN0b2M4KHsOhYbn+iddiicYkDSp8NAqhgjbsG5luse/TYiG1c4iemjQfuXdaD/JM4d02++B+4/PQGDycIZPXzuNKq/laHfZTC1/mnoYqH+R3hZ60PtLEmgMeor/xJ3RVc9c6CHdU+pIJip0yNHaPGdp5F/VOu+E3PzAv2Y+nU2M6dLO/ZqNwRjBv+QfDZa56/LR0p8flBnW2Ohme5PCKkNnxLbBfEKZPgXqkBbRptBih0morUa9TIE80kUZjmsL92ndBfvEvtFnQdGhxXxqaObD+kE1pRtHDzulbTlLatFSb8k0QhofuLNW8KgyPElUnJOKggj8BrxJrvnZTWgCpi4/wpmRpy1kIosSrEYDnJ4iiGJkpmIm3HUl43OMVI/tbGgvSx87LwgUHjS8byWUCYOG172FB97Se/s1hCm674GG3KqYNKhSECRcuEyctQXF0SzgbA0hOL13SfN/9D97cUH4QnJsrmg/4sGR1NskeqlpB1pOG01/qpTmDkgFc6YLY1c3gF7BX5D1IN36TS3frHp8HsKwUYnvvkqS9wx79CbetW1Zr/MmGDITmptmm+PfG6PAYi8NRlQqRLLVriURgvsMjAvU7HXKH8uvBP1ZdW/v4oWDDUyqrDbn01DY316FJgPiLQ+0wBufetvsXqClAUeKF0YSNppO8a6R/x5ch5cqX5ugVXsrvfGlz7gWa4SruUQ7N9yMQipf3gkvba8=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: observability
