---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: observability
spec:
  encryptedData:
    webhookUrl: AgB3IN5CF3AZhtO5ayeR7cJMssptGl7v7wzo2Bhv23B/j73tpY8bWed3F4BInzUjUIe8N9TfbsC49Nbp8CRSD76bfELABUk9Syqyv7Q6O0whpY7gPLo2JLmZxYdC2RGZudXutkvSZgNzQDla9Ig3Sbxjc24MqVktOyiNw4EOgRF8QQqkZXgtJU++mhnNLu7wEVLu9a8gPnoG3XOH5FkuNSp6D0hhgDpxtHXdrisntCP2O3PDmHsbFNJy2gA/vJA0aGSdTskbEkppcGESZhU4TCdTE8jHCBNjlNmRK4WwqiVZ8gfXU7psfnjv7MR+xG//ukcwcY8XrwfzowkgGLBZ5Fki2zV2LiBmT2QxtWpGiEfyYb2SkqdTcJMCBLfq3qqdeQRIOWzxzuPfeeU7PKZ+1EZdEaLz6sILcwHSFdDUe8lXUF4x52JfpDMkprfEkGZHWfYF4HEWtKTivbdiXVduQR1eWyR2WguafgQadwMxpJJgBjJWLp+s28nMvxnsvNV7iFMo2FKpyJL5d1RWX7pb8zdqtFwTkbnDDUy7b5YLOBWNZxMFDavzgHYbTMnLy/9pjrVdFnUMVSCbVCidPrURg+kvv3DTMTWiQ3153ufulY5NOvRvhAU/anedA4pk3iRrPfCppqaaKgPzPECxz7MZEcpnTeHzRLvqPyYiQxPj/DbiyDnLNoNe6KGDZ8xQZqtAeRdD09yqfQdPSz1dFZN49piikRhnY5PaiGx1JglbgExDvJq0hur1e5BqBgBxa0yIUaRa6La/H1Q3rsEBZ49FDiVlQHiXXFVazqiaLPEmZxk44/E=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: observability
