apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: notification-policy
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: "kube-prometheus-grafana"
  route:
    receiver: Slack
    group_by:
      - alertname
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
      - receiver: Slack
        matchers:
          - "severity = critical"
        groupWait: 0s
        repeatInterval: 1h
