---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-sa-token
  namespace: observability
spec:
  encryptedData:
    token: AgBXFb1Aqt0Q1nK6Ah2uN5d00INP3VtcIO6gY1wRp3CpMBMi0nzUWCTEodFWOE9+XCSJmHNyMXZzbYTutLzKrsY15tOHUQeb8YPSiLEHr5JGfy0erEaI6zLTQJ/fD8PvwJuS+eiukSzT/JHuYiA0mqJYwlG2A67ZeYQLRe3KhhfMd0jf1zbFGYVx0a2ND9IQruVuS+EXPrNeCwlSLZe6Hk6stMKvk9qFV2vSKro250sdpp6hb1D3RG5eXvOUJym0myRsZ5e0dwsuLqw/Vfi7LEYh7IzOxWJ8NRQp9JuT9HzGyMddfJC1Te/t7fISc29i3y8d+ATLOSIgyPEfL7LT7UxkNeEkwkXxyuzXNBJ8ckL0qqivh1kW3l6wqLj7H5w5iJPGcuUCZpnWLPvSQkgcdCes0JaP9yNMmGwtGFID/+ASp3m6XMmJk67i8cBBPJa8/PzlQpu4pZDAQbDdhL+4ot4lPhXntfHRkn9IwXOLPdNTOECXKplXPonb1+wks8zU8FlEAvHgfCIfGlN0fpdcnmzxGMIkvH/nZfDfV8dsbDqpwi5gopRaEcXV7d9Mw+GM2Zk1C1WTgA5bUoSBgRPM20XbS50+vC8634Thtss7U5KhBbKhocegFJDsuXH+nIPYYrSMZaEp+Gf0KiJ+i6OfMLadhbw9Ilwzato6lHOBkBowwUQaWqB6V+Kf6S7df8qd7PwcbHiSk4r8AsEBaVNIkwkgEmxP/Gkpvro6BG0BuGy6ZeMhez/NCRWlIWipmBWH
  template:
    metadata:
      name: grafana-sa-token
      namespace: observability
