# GrafanaContactPoint – gdzie wysyłać alerty (Slack)
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: slack-contact-point
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: "kube-prometheus-grafana"
  name: Slack
  type: slack
  settings:
    url: "placeholder"
    iconEmoji: ":bell:"
    title: |
      [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})
    text: |
      *Namespace:* {{ .CommonLabels.namespace }}
      {{ range .Alerts -}}
      {{ if .Labels.pod }}*Pod:* {{ .Labels.pod }}
      {{ end -}}
      *Summary:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      {{ end }}
    sendResolved: true
  valuesFrom:
    - targetPath: settings.url
      valueFrom:
        secretKeyRef:
          name: alertmanager-slack-webhook
          key: webhookUrl
