apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    accounts.blues.password: AgB//v2YHxQDo0gquEq7qmE6/c3QTzJfQeLKrE7l74Zb/TX6IQXL+6z9HXeDDlW/gpr3oZft97s7NYdkFA1wzrYdZRgqF0Wzk1CaCpiB3pYLP6bR+Lph9WdaPvt2XFQx+aXoBT2ihFv7esiuuEa9WqDtl12JqRX9XwIymll0OJ4YWY9ATcxPAnjupspp8wE3ZXewAAUR9lvNilz7tg95Et4BPS+/Y4Wn4iIcufLQIp9avzrZbTFuFjw3oyMJ8WxP1d44nf8RQvCdkaQ9AZU9cKUimZHx/uncqLjm+Bz+HXKDFV3u+tWZS6WTGmwi0CnJe8RICJ6l62d9ohqLl6cgNUXsr8D+Srtho36vvIy3cQLGBb+/3Y+XTqQVNXYieSAGstHDxgYTFs0bQzx6jGincavTu3s+rY14hOCdH0H4OT40yJ4Nhgn1BWIZZg+/TU76Q/YfE0jQse09vKkxE15weyg4n0Bq+YAfwPI8H2WQU77CuewSRV9vRGprogMcoDrGRSq942HLaaBE7sYikTvQMKH5bp8pf9jLJhqiUu/bQBycIoSgH2MYW0pJMzUk/veVxLPfJDPWzqoCrXUiHGREXC+Kgnx7qmTjNS87iqjqKEW9sc9ITUr4musbk6XK4gLai9QxfziEkNC/w6C/XopD2w0RJbCBr9lCXVpm3oNXPS3uGUYjH72spMlsD6x0AuFAuaAut3sbjuAsFne5hSKwSOGzP0YUern8DLgAd2cHAVYJ+hH03JGt8XvAegVfBpK0lPAbx6UFlGUnCKACLYY=
    accounts.blues.passwordMtime: AgA85SN646n6jd2QwoljIZJMDLdMOEmGFQX3nzZe3LLa2zLfznmcjxv24WR8wOtIQE4PKgESibAsVt++XDDbim9g3YjdwyznKuhN95omwfq3MnC0Yfcxe4CNM16JmSV0QX+wnMuEX9U1AIFVvikCnkohOC3bRknkt84ipJHGgPtJfZpaZtvQd6F9e1+EiloW1jlwOs9m1nEM+FNvTPndpYwJL7P2XNkGdKODzpvg0hvJaQiQ797jq37bz6dwQWlSLMzRN6xVc7Vse3QJggpk19US1J0wNGrTnBH+nJdoPw6FQJyHeDMtQowb6YWE243f9MeuI3+mVUl3kZ858yZO1v7ZtK9TLO4AEF9CF/r23MBgLigSe7Oai+Qy5Dpo4VS2THpNxzTq8+SEReM9yW49o8Z8t7rSMcV3xSQbAlKq0uhKuw7xr1YK6+jvcpkUvqlYknTKBezQ5iHZwltz+c49kDAE7MKPRu8QUUhu4WUjXqjUnvezdeXTzg4xrS8Q+TeCYEQhmhETnuxRs9hDzZrWsvbxhbh0OE9cfpgb2Knj8/O7mTYlEaQ2UTCzMSPM5S8P+Dlt6m+pWREAhz/RjJfTbFfA4Z8taRTGrZUoNtVd9EcZN7gTpoj09kclKZjd6atTKhjrBawc5VKSqkLlsiWZu9h/aEpt+Z+J0vRLUjSge6NP06ZAQGc2n0lrXadZeU8acALiQsRKAkSlRFh0e8NqCvCWN/v7iw==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
    type: Opaque
