---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: programmer-github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgC3YBjtuRPSNt/lqQIwjCyzyVm3MkE1kSO44Tm5u3HshftzBweaVgTyltnYUexTZnwyaKGlqVwnHPwPKsByV25H1DoyVW69kyG5cYJchkvirnDO31tPG/c7UdEKfSZeClsad03NycOQG1prHLR9ulHDsnOmmvjWyH/f6emcJhycNeD9KNy05Pbb3rol7yhoD7fwUJNRtAAW+K0zlnVy8YHG5WFzDdLh48M/CEvKOmjU49IvDdVWwX/yFsD7K+8ebM27YMT7xZ3ndYocX0XDOZGgVsDNReAgy6QlTJDZJvqATKF3MwCigIJb/FBYuzK403sFUfdw0w4t1zR6VidlIXQuVdcUjyZx1nmQUWh6XM2XyICqSb+tkkpy589Wra4uGhp5QTn9+Fp4TUGKX7rDcholDCd3JLrLv0MY4jyVJfMWyWIcw63ir4GPwbVSmZsaVDrO1jUWFgbJQtBFnplzri6EUKhjhm0mIkkVRVTBNOe+E+sEsnp7h8xduS7LD7+eGfjDs82LUvbP0fsmTrceVKVDTp1cTt9Dtk+rxdkAbDeXVYWNZKyEh82OF1AhDZWKJMED56dd4qb6RH45R5XHGWGABO/2GCfPeP2IUhMRaxqM6NvMD+7jZOLK6E9jmpKtpq6TZBU4i3fnrjiBHEB43wrtF9yVdRpqfhTOvg+two6c3LbEbbi5DoCDgE7fjofJXcvfOyPoi25NLSbMApPuxaYHMZU6V8EPlbDPWlXO3fFpvD0v91Ohq1Yw
  template:
    metadata:
      name: programmer-github-token
      namespace: argocd
