---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: programmer-server-app
  namespace: programmer
spec:
  encryptedData:
    database-url: AgA17HGuIT1cLxqpq4+9k/mrILO25ngQ3wx7jipy26KbQDC8ebB+NYBUoMtO7iWl78bOKtCAyxmutYO4SV0k14wAJ9xRdacKT2AXpIy5bDYmF9sAIFml2UCJh65LUwrPXj/xByO3auh0quR0j/2nEva2QaT6mNo1IRS17KmFhq3FAh7PNQ947mfNnOQAq9aewa9h7G8xGzpBfms/zvrM8XN0Gu++wpozX02Jt4PzKMDFMsyTTQVe0h2dDbXKedZEHZvJhUzakI2tUhtqcJhMgSOqck3hCQrUdY/2Tkz5uo5kMvI2gK8ulx8LxRGAv72SGVAKuzy6lsCEUsK62+JiXydb8bTn5U2n/x9csfIvQFZX9UW5/Spty2tJuUF4RtCgMH97sC4unIA4y8h/VGb68MgS/1iXFj8+xVkYPxOkQJahP03vt8uFYjgRRSsVI+SlEyKWuRLCuX9eaHcMnEo5ijfepN1rqIUHtGtoYfPOozd86KHUZCPtBYwVFJViibOyAS3Mx2tzJTuGzMaGAIYDuiHgKcp690velAomgAFCvaai00eHiKVCVD3genWNOyOGgdRztMLhMVxTBEmlwyufXfZFrVr8MMDzoyzolYR1SO6HACoFqfXRsDAf3i3H1EvqgoJaSxuBQFQvpDPVnjpK+J/p1YoycK4JuDPXXsSJzYEoyqHTHXooi3KdA1ILp2h/cu4skapnPzJybAFl14kTQPy41wODzP4cK3BhZd+8m1GEJxqM6qBL1un2LEsK841/k8y4mGuUYrQRXHtdmj5CuSMlqvc+3i9eTheN7jIkCE1o/5dFANDrVMgeT6Ys1o5Lw6yscOVxxqOG
    postgres-password: AgAV39HaECfJ1nNWbYegRTvBSSCSqvseQPg/v7uilVygNqfSUMGXWnT6DBr38KqCjxe1oweS+aOgVEqPTYONq/Ccb9gAnvLrioBAYL7vaHyklCHWcwyxSVd9i3iuKoFIZVgdAbG6pcUMdycTyixEa4v/8PQqVsj/86XE51s8ia/BJuKAEEbXQEbIjGIMwYMonjD89ZkeEvx1mVJMi8ZaPCsZ8VhJQupGU4NScNV15CkxXe/mD5BlyulrRNDT2Yf7++OxYDdgboFQGXnHYfSxU2dhpnjbmD3e6Gb1N8L35OHoKt93LyRDdZ5ey4TGOBT5hCpOjtCUod/2wgMyRXF8WVjC3+H/f8yzzIYO2VL4kNJxB1qIm4ijIQgRKXTJ1PLH7R9acpPsYq/Mxz2rb89EZ2GjLCypL23oaQpFyRtaTUshP/v+rE4+kZnsXpKZViYmn4W/ZECFM1Svo3jXhIpjIIuqWh3RUChLQ1/pII/VnDLcHgVmWAWAwNpvaj1XlWM4x/kfX8Udg+OQ4UDyRQ557d94cW9Z0Ay+fOVwJ3h+RtbJMsE1fERwRRUV2CJyS57A9Ftx7Gjk7kuISgOtb+8PWXV9TuqVwjrgLmqxQ4SMd8bYPxBaeGJSyR0NzGLHBL6sSt6wKqCIUFAlRq9Y2qJaXA0z/Qp1azR0w4C1a5GAucvywmLnyQ1rXCHRzlmvlV4HFwcKMihY98P9ck1PvOenQmfaq0z+fQQcNcxei8p4xiushS504dA=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: programmer-server-app
      namespace: programmer
