apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: programmer-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Blues-Brackets/spedimo.git
    path: programmer/helm/programmer-server
    targetRevision: poc
    helm:
      releaseName: programmer-server
      valuesObject:
        appSecret:
          create: false
        imagePullSecrets:
          - name: ghcr-pull-secret
        images:
          server:
            repository: ghcr.io/blues-brackets/spedimo/programmer-server
            tag: sha-f2bfdf4
            pullPolicy: IfNotPresent
          migrator:
            repository: ghcr.io/blues-brackets/spedimo/programmer-server-migrator
            tag: sha-f2bfdf4
            pullPolicy: IfNotPresent
          web:
            repository: ghcr.io/blues-brackets/spedimo/programmer-web
            tag: sha-f2bfdf4
            pullPolicy: IfNotPresent
        postgresql:
          auth:
            username: postgres
            database: programmer
          persistence:
            enabled: true
            size: 8Gi
            storageClass: ""
        server:
          replicaCount: 1
          env:
            logLevel: debug
            origin: https://programmer-web.programmer.alfa.bluesbrackets.com
        web:
          backendUrl: https://programmer-server.programmer.alfa.bluesbrackets.com
        ingress:
          enabled: true
          serverHost: programmer-server.programmer.alfa.bluesbrackets.com
          webHost: programmer-web.programmer.alfa.bluesbrackets.com
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          tls:
            - secretName: programmer-tls
              hosts:
                - programmer-server.programmer.alfa.bluesbrackets.com
                - programmer-web.programmer.alfa.bluesbrackets.com
          basicAuth:
            enabled: false
            realm: Programmer
            secret:
              create: false
              name: programmer-server-ingress-basic-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: programmer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
