---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: programmer-github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgBl9udJNqonQPZ65sZnKJlb/99MO6+fbbxDC3SAITnLdH34dxDgSElqeY4jwkKbHQvF4gEJRjTSOnV4FA/g4wNEwzeTctdnsf0KkfWQlxKrQt4SkTimfDBazPz3pHHoYxDgdwCyry6nLocunI8G5ef6z/EC8TX7gVY4FqQVOl2xptBk3BS0Y8/ZuzUB8Os/gvRyyDJcCPkfvL5NMwIivi6qPlD3/niFdiCNpneI30t3k0QHnb/K/cJOxmOE7oEK5OjghKHzEUUwGF+fotXvjvvKUyIA/42qwCZ7ifHyl8V5kHiENJN0ZBKvm16j8mA/+9+SqVNAMTxeBN/jCS8jBFCVlFdVieykeoPIaUwDM5aIUyt2MaFRMcCEnvaMUheFh47+9//hTxR5D/LK0M6WHacIZOuMQ9m+lfHJXi4xZmQr+dtNp+74qG3Z761X7kYzz0omMN4bs0sayj28LzMQnseS6B+uiBy5JvwBh6b+Ozw75qG5ZYQ+TtEC3hCImmMyy3Ah3XlnDfGv5AwOdrAHdXRpdCrvwqadZr3ldKiyDn5FJMwqq42HVpDHIFuKlVzZLYdzNXEctixnpLFhKTg0GjtzCssmPv8a+aydxTsDjXr4Tu/6CzZknfC6+MWKiHaHVzZJzkCLPOejykkKZwPBAkHZ8RBQTYavA6VZqzrZnjv8h6iDZzmzesolwcBetXlNrt9QH74HSmZDTzrOD92WqQQZR9ha3zGEDP0zt+kd1OrteCoj/nfXdk7I
  template:
    metadata:
      name: programmer-github-token
      namespace: argocd
