---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: programmer-server-ingress-basic-auth
  namespace: programmer
spec:
  encryptedData:
    users: AgBBfMO70kjg4pP161nL2GYZkeulmVlp2uycfM/LuP3ee/wghGfWlpF/44ndR0ojlq279zm8Q2FIVLKUi/h+ULn6/tP1htZ1cwute61K2005AZvjoa3GArYLF1o/Wct7HasX6Md8atn6llC/oyHtc82Sil/pQpx4x2DJEK4Y3ZwcUYwyrZ8yDW0lg474q+cTlqcz+AyGfADs9LqSmk0hPOkC0nVGQn8fxn99sqNrSdLAfur27NOkY97QiCcqBu/pYdgOqSkQ8hALNu0FUHcbamL6LJrwELi6qbyUyeHPWwOP227FjK9zqB87GORqHxrAIbDig4759wakWSlrB+UdSokXc5N2IG6XYDzn4dPt3dnEqtJcwCyIJkJCVRj6S1sK0fjMhav3CaoBSjl50cTxboRQFAG32lBuTrQnmM89osM8UlppksPWuMIH+cA5d4Qu00Vp1axr7C+Ldof1XowiK8pbkXh7Ph/pH9e7IQ8bVaB3SDVKPRwXK3y4ZQvbQbw1uKHLJtaUQUMyIAwnPkadvb26n7okOtccu7xrDoCT3NciWDvM0WtlPR0jQLCR6Z9/IDKhUilRXJA463jlok8+X3RbnvxFp0BapfSSD+pWNVKaarUQzldZkKHPdtyjeSH5y+3tS2g56WPWNRyr0+cyfjPdvrCs/BxblxjgwI55e+yQmanI5Q6QaSl5rmM/wu3NJZ52C04gqqbTvvbyEmz5ixIb9G/i55cflfWHIDBZnKm8kes6vvLT8vwERvwJlOM/K7s=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      name: programmer-server-ingress-basic-auth
      namespace: programmer
