---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: programmer-server-ingress-basic-auth
  namespace: programmer
spec:
  encryptedData:
    users: AgDo9OBqi/Kz9Q0S3Dge4tnxMyjHme01ub1IdBdlRzWMQbTXvjXuvy+HZoH6U2NhYLaASg2dmkKSM0DMcBDZFUI7nNCkDrnwLjDNBrYo3RUOdzBDpdJZ2tgy/KrazgZpvtOVDlwjx93m2xPUu782izbYXKqO2SKxDlbCfe9jSqRd/eIHW5LtiH2QwWnmXqS7xfDlKv/WMB0DBQuuGiC7tubQM9RJRX9bfV/KPsPLNH8l/Q6J4FMtW/vM7RGxceXrQOeKc0pNDyBrIoeAKqor2YaYCMamh+qq7DkU4/xZ8GT7sHxnzJvENuJsl6GV9mFWo8D0xYwXOQhqD5Uzfq4/cT+TLQdCj7OIAaALU26xvrslbkbPzBonmIH5jwAVtfOdt5s+iWkeQLueabYh4UzI+BGrgeLbdpC7eS9Q5SHxdvtYS5jAG7JODysPzdj3gARIMl1u7bV5+idktfbNJXZIL15F4gHBO+64cn6Jxu8AVx1zDggTb9Li7WTz1Rx3OdNbsMAgwHB6MWLpM/kJB9o5I7aRN5wwpU/YpQyFDMAjkb8ELygGT3vaI9HqFwSVOmRTtSQNHKXoeWX2fT5FoqTOELWtUJOk3IVEpRzoTqOy2F1HgKMw+vosF5380wWlXKtFmvn7u7JC1l2/tyPmYMw7Ld+c+6bGcwgYuLu5U1/93P02t+TQALnoYG82GipE7ibhu9wR07DyAd2w/I5JvRjBgJzPqHtHzp0FpftuDsuRKD/HI/mopCAqsjtyr6RMUGmWhj4=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      name: programmer-server-ingress-basic-auth
      namespace: programmer
