---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: programmer-server-ingress-basic-auth
  namespace: programmer
spec:
  encryptedData:
    users: AgA5MBJcHvpwTZL//RtapF/fX+3I2PhccDRPM6RQXXU7DJ9kPKvwMx4hKKK/TiTzkdm2RnkTRhlulzRVs7r45pIlIrgM3gtnBuszfp0koIHVyqqerMODhBNfqqefXw7JElGSPKJHxRme3I+XqCtm3q73hagITlAcpz/1HI49F7rwf/njQWxCG1VAjty1J5Ujc4Z9vWPaqg9bJJrPgKOZiGy6sCS5wEbYRaGAOx4OKHb+IXNhdXjxMw2pkIYmiAQ4DpZ+ZUPObbA7Ba42VMRuiJ/tMGBEcUDTxee3rl5lwmHVSy+7gGGytkD9AXdK/9CK6DJVa6lCI2Z9D8DAxesm49fHHr0p3kaAUy/HgWZ8Ka5TKXCa92o7TWKYQs1Mwh4sp9PC9Gmu0tYKP6sRsPkfRzO/ZnI3aIjZOh2Mzt7n5zbgzSJ7QAu5bMS+4gzBcks6i4Dh4kN6dTZYsSV3gx2x8N3hMxSSzdjo+FlvXX3SuwduZT7rwI+B/scgadqFEc4S3tEuTjEiplAdDRKvSAYegfRPfcdlQtcx2NoDdrEzsjDpjh3FBrpxLfn77GgAvHLcbqUoRs51s466ODwGF/p5euMMzm5/K4d1hoky0utyuizOl+Ve4wzoHXacjEGL/Buz7DPMCp7Z1DKUQGD3o68FVLT24AP1/bzjT9pdlFX9pnXVN/jIYw0yGreWK59njwuyuoPjhEX9G+9rg0JAnXnDO7a/3bixUTOiX1f43ikXikZELCnGnVPCBfIRv2pt8nEc/OQ=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      name: programmer-server-ingress-basic-auth
      namespace: programmer
