---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: programmer-server-app
  namespace: programmer
spec:
  encryptedData:
    database-url: AgA6LOISNfPxRs9Qd1AA2wjjNp5zEZ8ThRj75NJw0xi+q+uABtlPMuOCLExdE16AG3DVlPEy2PLGLFup9EbShn3aROI0aPeQs0BvdcgYu+clCrN5iQ26jhCUIeG6+J2SN4a47T2ZpflI3UlZMCX0ANEDn9SuoSMzewdtFYu5og1SsZNOozAHFO09Kycp9nYCmY0XDoSEfveH3K5tmtl6w3EPuNDOM6kT9L8TBPwMUxsnHWJ0XYaoLci7k8WVWjad7eIsJF+B2ZSx8nUjG0QvrExnAhjXKy80rramgZgX74z9YJ29+3pjGLL+/oxsKO/medpigp6Er4a4xTUvy2VmRXW1L2i+Ub/JqABU8hyyQJecUFeyDlIKLzbMZFMvNacM2v3UPaInwHz9q2CRAMHKlySSoqu+oFbO1gIP83IZrIx6sxtoku0jYfkaqq7J6gFDEFJFA7+3GbSHwKlq5tvCC/8/Xb41e502DSK5lHWCP1wMGZzHCDbb8iFHtMs2582d71T+7WoqRZDIE6xb0lTfHpyL4lDmTcic/rTlGVN14Cz/7OmYVmUnNDioi3g0mGNx64bxU3OWgt7rhQQeDTIu3pdnSfgAMkNDEfgUo/XclgvFoHewJyQbW7mZ4TL/nS3/LwhJYG3L489pljvQNblb3Rk+plNeyC3jQGIrWQQxACBOdsOrUiIxlG6N7YLwYyiD6wuZD7wx2PjrTjh3VUTY1IUC4JACsSBXSCBfXOEQkeHtY42t5ZUEUIxyc/7BXUbdjB2TY3XFupgcxtXs8Jv5bs4B7cKFrTL71y5wOsAOg52ADHnAf5Rs1kVNKq0YtTbJlwdf9keFyxj+
    postgres-password: AgCaQpgyF2uSB6UufzmN7TxaT3TPWBZ9yKU+zOQZfz0j4JQvvzyCBOBvFJzuH8EwK81WFCRR2P+jQa9+g4w7bF6sv+LiVz6FqpwB6vIWPDzubx1MH1Makzmo0pEVv2Mk41sH5gcq53Zwa1rtTpmCXRTCBr9bTj5w5H4Sswsq4VdPeLJZn4Jn/i8FK1H0TEcO1PdKFHfJKrXnII4G9EXldbLXbsROScc+e5fBt7/3xRd9WVbrPZUR0Za5XxXbMmQcQZNtDlmMWHiLLFRpaiun/bm15hlhiIe/wV/ccA9rUuhiOGPmepE061cDsAPCjGj3+/5nPWVeeYOdKq09Fh7enIB5xSo/Cg7eXjfdk5opI+2e2ngHryzq435AzX9OuVvGCk8kJ/r9L5HaIosim8N1l+VrJGQUlwfgClxvEfx3cC+eA47ugPltDARWOXKEcb90FV6voE0Z/c5QiFaAZI1tlfnM5rL9xOJyZJbfVuH/4T9X8Ee5b/pJFM6/p/pma/KWWGHZsFhriMX1Ij9CC/0lxz5NXwe679Btcc1P9h4i3gmz/wwywRQXuzIBtleaqrqM8z+mOLC5zqmM3ze5QykHVWe9nb4DyfLRM1vmgX9s9Tkd+xnU51GHf+38/e8+Itf+BFaDcK7c1A1kIkpMyHc0bPBD7gIBcC5o8WwBhQXBWQeur5Ho1qoOhBAr33eGkIxS566w6nZV0WmsTT1ONzFgNffxoVHV6kHRN+mXpM8Jl5necFWe8wQ=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: programmer-server-app
      namespace: programmer
