---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: programmer
spec:
  encryptedData:
    .dockerconfigjson: AgBKTaLiqKnyGKDWa49HtZGE4DRft1ICDLG2YAvYz7J08sxnMS36qk03LzWUK5CtSwnYlBOx/4GHM/u7Wo48YeIEknW4ibQcL5xvk9M7ozTtkcTqpGVHH0GYCQB2O4no/mH107G7WBPiBj35lEtnz/eLDyo4un/POZwhrl398yq4DH505cGhn22b6ateNAVyQPqBkOaVIsH6+EJPcQKgzmupOnZVPGDTx8skQoFYRI6HwsDzXyUw5g8KPTok7z+3+Oc5js/3CADbxIE5pJCkrEITR4WDHm4vUaEBOX2KOukyjw4wZTUjLnGE6h0/3IOudmO8JzR+GC3g45yFO2RKr0EWdlcVkyYFKzzBm2udYsX+CIYRuYV3DIszupnyCOWejog0cdy4JLg9G76HaoFyc4AdX9rEaEeHWZ9ek+np5tVOB2yZWxZrxDrKyLahFEwBhRb8GPLXhxCnPD0Fn2D0GsLCC2JEMcae4x8hrA8QseI7EWGTUybuh+Rw00SttFvOPFvMIqQSsFAz3vC8gKHH/GNNcriPUyRYqL7Jg901RJHeaZBE86t4gQM6OhrEebNqFNbb4IZADEBDU6Y2sW8M5/wQCJtYrBKxSRzcoJWqwb/qaLqHDPadNupfclCejgXaQhkxn4LJxf0A2431sKucBjYrxdOoGIZ5+B4lDilbGcXqSaUOATczJ+ww9vmU2PDehTLnVLKci+7aEbHaVDj/XzKtifIIGQID6AJTVDH1m0cbeo91P/jFji+BqWlZfsOvufBb4IruD/yJUGv6aE4i+LyVMEZKjho0SUDz
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: programmer
    type: kubernetes.io/dockerconfigjson
