apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: programmer-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Blues-Brackets/spedimo.git
    path: programmer/helm/programmer-server
    targetRevision: helm
    helm:
      releaseName: programmer-server
      valuesObject:
        appSecret:
          create: false
        imagePullSecrets:
          - name: ghcr-pull-secret
        images:
          server:
            repository: ghcr.io/blues-brackets/spedimo/programmer-server
            tag: sha-a4e3756
            pullPolicy: IfNotPresent
          migrator:
            repository: ghcr.io/blues-brackets/spedimo/programmer-server-migrator
            tag: sha-a4e3756
            pullPolicy: IfNotPresent
          web:
            repository: ghcr.io/blues-brackets/spedimo/programmer-server-web
            tag: sha-a4e3756
            pullPolicy: IfNotPresent
        postgresql:
          auth:
            username: postgres
            database: programmer
          persistence:
            enabled: true
            size: 8Gi
            storageClass: ""
        server:
          replicaCount: 1
          env:
            logLevel: debug
  destination:
    server: https://kubernetes.default.svc
    namespace: programmer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
