apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: programmer-pr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - pullRequest:
        requeueAfterSeconds: 60
        github:
          owner: Blues-Brackets
          repo: spedimo
          tokenRef:
            secretName: programmer-github-token
            key: token
          labels:
            - preview
  template:
    metadata:
      name: programmer-pr-{{number}}
    spec:
      project: default
      source:
        repoURL: git@github.com:Blues-Brackets/spedimo.git
        targetRevision: "{{head_sha}}"
        path: programmer/helm/programmer-server
        helm:
          releaseName: programmer-pr-{{number}}
          valuesObject:
            appSecret:
              create: true
            imagePullSecrets:
              - name: ghcr-pull-secret
            images:
              server:
                repository: ghcr.io/blues-brackets/spedimo/programmer-server
                tag: pr-{{number}}
                pullPolicy: IfNotPresent
              migrator:
                repository: ghcr.io/blues-brackets/spedimo/programmer-server-migrator
                tag: pr-{{number}}
                pullPolicy: IfNotPresent
              web:
                repository: ghcr.io/blues-brackets/spedimo/programmer-web
                tag: pr-{{number}}
                pullPolicy: IfNotPresent
            postgresql:
              auth:
                username: postgres
                database: programmer
              persistence:
                enabled: false
                size: 1Gi
                storageClass: ""
            server:
              replicaCount: 1
              env:
                logLevel: debug
            web:
              replicaCount: 1
              backendUrl: https://api.programmer-pr-{{number}}.alfa.bluesbrackets.com
            ingress:
              enabled: true
              serverHost: api.programmer-pr-{{number}}.alfa.bluesbrackets.com
              webHost: programmer-pr-{{number}}.alfa.bluesbrackets.com
      destination:
        server: https://kubernetes.default.svc
        namespace: programmer
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
