---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: programmer-github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgCaxVl2FLkfRyWjXH9g0sVLBogkVSYS34RamIuRTi3a0jbNz2lnEGRgM9/clnoS7UTvh1L+TmtbGJPZ7Uo1pdhbrTshZi9scNlOM1iY7/GcteVGPJMWCmQJrFnTitjbCvPPvXDG4JCMEPK9lXrQg9ip05Kk2Ego0q1id0ygpiKIz49R4AApYDATDY4XKua+PBfbAxqwixGFDlO7KFOxNwb7CM8V3LYoHoFEsPyk5pA4bAz5t2Fmp1XFfpN3BjqtvIbT6E8x0K3JX26/S8BRZ7L+VqicqTvrV39Kba+qVbsgCwPnMml5DP8d2oNb3uNEz1W+jsA97FcEZhKdIfh3qnIKbYN4PZbEE7DVdWTsefHk24AQBJnF2+XJIjYfYaq0dDgsHLpAB5EQOJDBi+CMpaXktKwqPwl1SPpkvDG63pyM3ucWN0EnOFoB7lImBZV7picR5FP4WrELpN5/uWGQ/XGk7IUP7Gh1tQHXWCAn9wEA49l48ER2f/vAYhDDyPmBPz+25hoCUMV5KjEcq22QgK+y9iCsJOdDiYhk4PkbjG3SsOApqiI9qg+D8WCOfTcCzrS42bZrwMAGOB1Yss1Irc4WJzvCWWDlS/BLlJm+gD8dUY7iMOBsrhhJtbEA9TQxGpKen2iaLbfEByMiCx3nhRs6K71BD7FrzhAsfAgWA9aIcawat6Y+SNzEhQpXxzpKldFPfxbaatpHa1F/Q+8gDiy49w6yGrPEH5zd+D5SB7qjn6G+7ivxunzF
  template:
    metadata:
      name: programmer-github-token
      namespace: argocd
