---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: programmer
spec:
  encryptedData:
    .dockerconfigjson: AgC/Fj6x9ba7z8HWO2i3DCPQRGqbavDDi2/ZbLRi+BeckacVE+S41VgKvTMkjenVNo5pLwelpYFILx3o/P1rN9H4f6wUzeDvvZ5U3UdwVF66o7txJoD+wYA65d2Y4oMipfUr74TWbycKlqxT1AR2oQWCtcJZT+mystv8vpMjKfFtvAA7GTAeaqUvGFkC6nB/J2+l8kfLazVOinBVDCemtxVW9oLKo/YkBn6C6X+uS5tsMBEqYckktpo9aJ7WdRIKddPTOhqLTvpCXtWaqafQzQq1XTY/iL3DELZnuJTOEHMJPw0fbi6+WPkI+ySjHi2kk8xgT0MNDl590Aj0krS1EtmwjK6M3rWhrnS9K2o+lx6UMF+illpZ0HwXAHfVCDPXiKi3VhOQDQI8yrgV4w7gWPVT12iiVDfqskq9qcKj4J3MAYdXOnn3+iT1VpXTJ40Poc4BUdlSb2Z8/SdK34EFtYlpUlVHUhNQ3y8A0Y/k631qNP1De4aMjFj5FDncqmkXNtGa1hPZTM7q4eaUSZZSNcNuKD8JXm8kSmcgjeIVmB/yucRxrCSEb3l40pRNt6dfsTHCLcY4cxzRwlQmVV8QfxUUty+RnWb5aRONCFcL1s5AVWFqEcX5cPEx2MUEjgtllz0i13njGiX/Tb/1eTyqe3s0tx3ksdenyC7e1CeRlQDzOrGRBAb8Gw2RWle5Fnltv2wUcqzbwznN7QbY9reao7XoVcWKDAUfBxyPURPjoaIGyis0MFms0EIgrYM4vbX3tp04S7K6YRMzcaZrvPR+SZ3HqVhZ5sSY4cC5nVqRiY6dzugTt8CB4LMewAjlp3PDbmP0
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: programmer
    type: kubernetes.io/dockerconfigjson
