---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: programmer
spec:
  encryptedData:
    .dockerconfigjson: AgBpRc5E52ARXlXGXxX+Ptfe1rCjY3jgjpWd/wkhGgOaDWgIUsTxvICrLsiDIh2+fZthsEEimiP+97bzFVZFYhPn9pHZawLbZfgj0eDnZ1WHMKQztyn2u7RVFuUTdWE5YY8mJoX3b97T94msayZSkvqf1dUFCSgunHPa6TTiHCQf1ymUAKNZnIXkVKiq8fun8Tft9Lnzlbg0xKCDxy1boFJDYtK5A7n9Rc8vQK67lVLO/voT6DfWnP26DgmQHDE871F3iJJ++T1Ig42lE1Rkxgzlp1S9uTGaCkj0kjALKOCN+EixyWLEsVy/EpUrNz895nGz2iT+d7uLLHBA7ZKtePq0WrX4Z3dDgynSc7AxcDfjsMMyN3iZWDdr6aqdwxQZHLe74n8ZpYdCKjjEdhjWHX3V+K8v5mwHSJlLW2WM+21I5jc9MuS7vL3NeZQzaG19qDzTbCA8HU7NjMExdfeC4GmEETBZkqa7pYjfnO6N4arKzpziBNOMDaeyz5B4AAThIrGnzH2yYiz6fLKaznZJjJaGBbMNAGj00fa0+mpf91zJlH0fhDnrMk6X0fmG/vlxx3slm6vjJ0AyrMBPST8W0AHsOsqkCeUfDZMpEy2IyMbhz4GDnqKIXsyytY4FJautJxSGlMRkDaT6tydyBkA7NVMElRj7CpEjFirroSgFymXUQZq/QuPP5dVq0rRYyYRjgkxfk6yeUk6f+L0X5Np1dE3lWB6nlN1Qv+RLiuPs5OapCGilkbaIsoSDn+kPWEIpvpXvCKofHnb5315e3MaHqa7gbMB/+KclvgO1ZslpWqsgeYAsrMHqp0RnGBaXNnwsXxpT
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: programmer
    type: kubernetes.io/dockerconfigjson
